### ISSUE TITLE
Trippy 0.8.0 installed via WinGet stuck at Awaiting Data.

### ISSUE THREAD

**Issue by ShaguarWKL** [fujiapple852/trippy#693]
I am unsure if this is the right place to try and get help but googling hasn't helped.

I was looking for a Powershell version of MTR and found discovered Trippy so I checked in Winget and its a package on it. Installed it via Winget, ran it with elevated privileges via gsudo also tried in running it in a new instance that was opened with "Run as Administrator" just to make sure it wasn't gsudo somehow not elevating privileges.

I also made sure that my powershell instance was running ping and tracert properly before making this post.

trip 8.8.8.8 was what I used to test and below is what I got.
`Target: Imperator (192.168.50.69) -> 8.8.8.8 (8.8.8.8)                                                                              2023-09-30T01:00:27+07:00││Config: protocol=icmp(v4) as-info=n/a details=off max-hosts=auto                                                                           help settings quit││Status: Running, discovered 0 hops `

The clock is ticking when trippy is running but am just stuck at 
`Awaiting data...`

**Comment by fujiapple852** [comment]
Hi there @ShaguarWKL 

Please see #656 for the solution (TLDR; you need to allow ICMP traffic in Windows Defender).

I think I should also add a note to the Windows installation instruction as this does seem to be a frequently asked question.

**Comment by ShaguarWKL** [comment]
@fujiapple852 thanks!

If you do add a note, here's something you can add to it.

in Powershell
CREATE RULE:
`New-NetFirewallRule -DisplayName "ICMP Trippy Allow" -Name ICMP_TRIPPY_ALLOW -Protocol ICMPv4 -Action Allow`

ENABLE/DISABLE RULE: (for those who don't want to have this run all the time)
```
Enable-NetFirewallRule ICMP_TRIPPY_ALLOW
Disable-NetFirewallRule ICMP_TRIPPY_ALLOW
```

**Comment by fujiapple852** [comment]
That’s really useful @ShaguarWKL, thank you.  I trust everything works for you now?

I’m also investigating the possibility of having the winget install setup these rules as well.

**Comment by ShaguarWKL** [comment]
> That’s really useful @ShaguarWKL, thank you. I trust everything works for you now?

@fujiapple852 yes once it was narrowed down to firewall issue. I have it working now.  Thanks

Trippy is definitely a great successor to MTR. If this come out 15 years ago, I wouldn't have had to deal with the stupid Ping Plotter and recommended this to my customers in my previous life.

MTR was great but when you have 16 screens running 4 instances each at a NOC, it gets difficult to read without visualisation especially without alert capabilities.

**Comment by c-git** [comment]
Interestingly I also came here from ping plotter but not because I wasn't satisfied but because I don't use windows anymore and ping plot well... does. I actually want to build out a GUI for trippy (optional add-on kinda thing) that would be similar to ping plotter giving you bands for each thing your pinging.

**Comment by fujiapple852** [comment]
Thanks for confirming @ShaguarWKL and for the kind words.

Regarding alert capabilities, I'd be interested in your views on the discussion that @c-git started on this topic in #636.  It would be great to understand your workflow in more detail to understand what sort of visualisations and alerting capability you find useful.

For now I'll close this issue since the original problem is resolved.  I've opened #695 for documenting the Windows defender setup requirements.
