### ISSUE TITLE
Allow customizing columns

### ISSUE THREAD

**Issue by fujiapple852** [fujiapple852/trippy#757]
The list of columns shown in the main table is fixed.  It would be nice if users could customise this list.

This would likely take the form of:
- A command line / config file entry to specify a list of columns to show in the Tui and reports
- A dialog in the Tui to allow modification of the columns shown in the Tui

It may also be useful to allow adjusting the format of the data in each column and perhaps even the column widths.

**Comment by trkelly23** [comment]
As you mentioned in the issue https://github.com/fujiapple852/trippy/issues/39 it would be better to work 757 first.   
I totally agree this feature is needed before adding more columns to the frontend.

**Comment by trkelly23** [comment]
I published the first changes for the custom columns.  So far it allows for command line and config file choices of columns by selecting single characters.  It doesn't customization of individual headings there are challenges in borrowing custom column headings &str values due to the &mut app passed into the table.rs render call.  
If you don't mind can I get some quick feedback on:
https://github.com/trkelly23/trippy/tree/Allow-Custom-Columns
** Not quite ready for a PR
